/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DragoButton: (typeof import('./../src/components/DragoButton/index.vue'))['default']
    Test: (typeof import('./../src/components/Test/index.vue'))['default']
  }
}
